export const GET_CURRENT_USER = "get_current_user"
export const GET_ALL_POSTS = "get_all_post"
export const CREATE_ONE_POST = "create_one_post"
export const UPDATE_ONE_POST = "update_one_post"
export const DELETE_ONE_POST = "delete_one_post"